spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:mysql://localhost:3306/hway_db
    username: root
    password: Uni12code$
  jpa:
    hibernate:
      ddl-auto: update
    jpa:
      show-sql: true
logging:
  level:
    root: info
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/